### ISSUE TITLE
Support for ArrayBuffer

### ISSUE THREAD

**Issue by xcambar** [keybase/triplesec#18]
Hi,
it's all in the title: though I supposed it is planned, would you add support for ArrayBuffer in triplesec?

Or could you provide some help with a gist on how to cypher from and decypher to an ArrayBuffer?

It is blocking for me at the moment, and I have to use the (very good though) CryptoJS  as it has this feature... Further more, it would provide an awesome performance boost!

Thanks!

**Comment by ColdHeat** [comment]
Not sure if `triplesec-3.0.14-min.js` is the right file to be using but that is what I used and my code would not work without @xcambar 's function. 

```
function arrayBufferToTriplesecBuffer (b) {
  return new triplesec.Buffer( new Uint8Array(b)  );
}
```

Without the conversion, binary data will be mostly correct but have some oddly incorrect bytes in output.
