### ISSUE TITLE
SHA-3 is not a standard yet

### ISSUE THREAD

**Issue by stbuehler** [keybase/triplesec#30]
SHA-3 is not a standard yet, so it is strange you claim to already be using it.

The final SHA-3 will probably include Sakura as additional "padding" (probably something like `111`) before the `10*1` padding, which I couldn't find in your implementation.

At least `@blockSize : (1600 - 2 * SHA3.outputLength)/32` looks like it could be the parameters that are actually going to make it.

See [kelsey-email-moving-forward-110113.pdf](http://csrc.nist.gov/groups/ST/hash/sha-3/documents/kelsey-email-moving-forward-110113.pdf) from http://csrc.nist.gov/groups/ST/hash/sha-3/sha-3_standardization.html and search for "Sakura" on http://keccak.noekeon.org/

**Comment by heronhaye** [comment]
Triplesec Version 4 uses the SHA3 standard now.
