### ISSUE TITLE
Weird _key bug

### ISSUE THREAD

**Issue by SimeonC** [keybase/triplesec#41]
Using the following coffeescript I get this error: `Error: in KDF: Failed due to scrubbed key!`

``` coffeescript
_key = new Buffer "some_key_here"
encrypt { _key, data: new Buffer "secret_here" }, cb
```

But the following works flawsessly:

``` coffeescript
key = new Buffer "some_key_here"
encrypt { key, data: new Buffer "secret_here" }, cb
```

I think somewhere in the triplesec a _key variable is not being scoped properly?

**Comment by dr-dimitru** [comment]
+1

**Comment by maxtaco** [comment]
Encrypt needs parameter named `key`, not a `_key`.  Is there documentation
that says otherwise?

**Comment by dr-dimitru** [comment]
@maxtaco thank you for reply, but I believe my error is passed values into `encrypt` method. Which types of parameters it accepts in browser? `Uint8Array`?

**Comment by dr-dimitru** [comment]
Found an answer by myself, but it will be more better to see it in docs (API docs isn't readable and didn't give understanding of how this thing works), so it accepts `triplesec.Buffer`:
```js
triplesec.encrypt({key: new triplesec.Buffer('string'), data: new triplesec.Buffer('pas')}, function(err, res){console.log(err,res)});
```
