### ISSUE TITLE
404 error on browser version

### ISSUE THREAD

**Issue by davisable** [keybase/triplesec#43]
The browser version linked in the Installation section from the homepage ( https://keybase.io/triplesec/ ) leads to a 404 page not found. Link is:

https://keybase.io/triplesec/rel/triplesec-3.0.0-min.js

This is also causing the page's "In-Browser Magical Demo" to not work (since it requires the file above)

**Comment by malgorithms** [comment]
Ahh, thanks, this should be fixed tomorrow. The latest version is 3.0.14, FYI:

https://github.com/keybase/triplesec/tree/master/rel

**Comment by SparkDustJoe** [comment]
The demo on the page is working again.  And thanks for the link to my C# version.  If you guys make a V4 or do drastic code changes, just open an issue on my repository and I'll address it.  :)  
If you need C# examples for that page as well, for the code snippets, let me know and I can get those to you.

**Comment by gburtini** [comment]
This has also been fixed for a year. @maxtaco - sorry if I am annoying you tagging you in these things, is there someone else I should tag to to clean up these issues?
