### ISSUE TITLE
AES Implementation is not Cache-Timing Safe

### ISSUE THREAD

**Issue by sarciszewski** [keybase/triplesec#47]
https://github.com/keybase/triplesec/blob/ecf9dccd9352d624a0658f8e38c63a9235e268c7/lib/aes.js#L148-L173
- http://blog.ircmaxell.com/2014/11/its-all-about-time.html
- http://cr.yp.to/antiforgery/cachetiming-20050414.pdf

**Comment by Aranjedeath** [comment]
Potentially great additional place to start

https://crypto.stanford.edu/sjcl/

**Comment by maxtaco** [comment]
Thanks for the comments.  @Aranjedeath, seems like the SJCL uses the same implementation, so they are likely susceptible to the same attacks.  Please correct me if I'm wrong.

**Comment by maxtaco** [comment]
BTW, it also looks like the [Go implementation](https://golang.org/src/crypto/aes/block.go) also uses the same algorithm.  Any good implementations that you recommend checking out?

**Comment by maxtaco** [comment]
After a bit more reading, it seems constant-time AES implementations seem [mainly academic and not commonly implemented](http://crypto.stackexchange.com/questions/55/known-methods-for-constant-time-table-free-aes-implementation-using-standard). 

While I agree with the points in Dan Bernstein's paper, the practical take-away is just to use salsa20 instead, whose main design goals include no secret-based lookups on the critical path.  It's a little bit of an advertisement for his own work.  

Well, you've come to the right place, if you encrypt with TripleSec, you get Salsa20 as one of the ciphers, and an adversary who successfully pulls of a cache-timing attack against you would still have to break Salsa20 to recover full keys or plaintexts.
