### ISSUE TITLE
Remove "browser/" from .npmignore

### ISSUE THREAD

**Issue by mcallan83** [keybase/triplesec#52]
I am trying to use tripelsec in the browser. I have install via NPM, which is common now for front end dependancies, but the .npmignore file is preventing the ./browser/ directory from being included.

Would it hurt to remove "browser/" from the npmignore?

**Comment by gburtini** [comment]
Handled in #56. @maxtaco can you close this, and perhaps the other solved/unsolvable issues?

**Comment by mcallan83** [comment]
Just tested this and it doesn't seem to be fixed. When installed from NPM, the browser folder is still not included probably because the package is tied to the v3.0.25 release. Can we maybe do a v3.0.26 and update package.json to reflect this?

**Comment by maxtaco** [comment]
OK, live in 3.0.26. LMK if it's not fixed....

**Comment by mcallan83** [comment]
@maxtaco I pulled in the update and the browser folder is now showing. Thanks for updating!
