### ISSUE TITLE
scrypt integerify implementation selects the wrong word from block

### ISSUE THREAD

**Issue by ericmj** [keybase/triplesec#53]
I think the integerify implementation is incorrect. To quote the specification [1]:

> Integerify(B0 ... B2r−1) is defined as the result of B2r−1

Which can also be interpreted as select the last word from a block. The integerify function in triplesec on the other hand selects a word form the middle of the block.

```coffeescript
fixup_uint32(X[0x10*(lim-1)]) & (@N - 1)
```

The `0x10` constant above should be `0x20`. I would guess this mistake stems from this code being based on a reference implementation that used 64-bit words and the triplesec implementation using 32-bit words (`Int32Array`).

[1] http://www.tarsnap.com/scrypt/scrypt.pdf

**Comment by ericmj** [comment]
My bad, it seems like it does indeed select the correct word. My confusion comes from `smix` using double sized arrays for some reason.

**Comment by maxtaco** [comment]
Thanks for checking out the code. I am pretty sure our implementation
outputs the published test vectors so we should be producing predictable
results.  Thanks!

**Comment by ericmj** [comment]
Yeah, I found the test vectors eventually which was of great help for my own implementation.

Thanks!
