### ISSUE TITLE
Link to php implementation on website

### ISSUE THREAD

**Issue by lyoshenka** [keybase/triplesec#57]
Please add https://github.com/lyoshenka/php-triplesec to the list of implementations.

I'm happy to file a PR if you point me to the website source.

**Comment by gburtini** [comment]
The HTML apparently comes from here: https://github.com/keybase/triplesec/blob/master/index.html

**Comment by lyoshenka** [comment]
I don't think it does. That page doesn't match what's on https://keybase.io/triplesec/

Either way, they added a link so this can be closed.
