### ISSUE TITLE
Browser test page linked from https://keybase.io/triplesec/ website is broken

### ISSUE THREAD

**Issue by grempe** [keybase/triplesec#58]
On this info website:

https://keybase.io/triplesec/

In the section of the page where it says:

> How do I verify the implementation against known test vectors? In the browser, you can visit our-browser based test page.

The 'test page' link pointing here is broken:

https://keybase.io/triplesec/test/browser/index.html

**Comment by maxtaco** [comment]
Thanks! I just deleted that link.  All of your proposed text fixes should be live now. Thanks for your keen eyes on this stuff.
