### ISSUE TITLE
hack-and-tell slides in standard format?

### ISSUE THREAD

**Issue by jpouellet** [keybase/triplesec#61]
Any chance we could get the [hack and tell slides](https://github.com/keybase/triplesec/tree/master/talks/hack-and-tell%202013.10.22.key) in a format which can be viewed on not-OS X? A PDF or something would be great.

Thanks!

**Comment by gburtini** [comment]
I was going to submit a pull request to change this, but I actually think the slides don't belong in this repo. at all, so I propose they be removed entirely.

That said, here is the slide set in `pdf`. I may have reduced the fonts in the process, as the file referenced fonts I do not have installed. [hack-and-tell 2013.10.22.pdf](https://github.com/keybase/triplesec/files/1316314/hack-and-tell.2013.10.22.pdf)
